
// if you're using pannel carefully edit this part.

const sessionName = 'session';
const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSUhhdDZrQ3ZPb3BwZDJVdkxsaW5COUgxQjlEV0NIZDdPa09Ya2VBOVFHOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieDEySEVNTktaZElWRk1MS3hxTmdHZHlaU1BkWGNpT0xZYWFWTWN1WldWMD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ5RnVUano0YndZUi9EQU91SlhGRytFUndpVjBQenVqMDRNbkVHUU5wOUZvPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJaMjJXaU1Pb1NVeVhPNWZ1YWVQeXNOR3BoNkxJTElRTG4ybkZLUHdhQzJjPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlVEZHhrdERtTVpqd0R4MEREalhNMkVic3F1cnU4UWVJdjdodEdhRHJmbjQ9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im15TDZwTzlzM2NtS1lSTWNGRTJmNUtrKzNUV0dudnFLWnhiVHJuSkNZaFE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieUNZd1dvMGQrY1R1SzNHbWpiUVhlK3M2VmhQVkdtT3pCTG84MnhQZ1oxUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQjhNY0RHUmxOZUpXRFExMnRjR1ZqQkVzOHJScDZDVzNyNUo0alBVcUxDVT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImMyb1pvdnBkUjBjeUdQb2YzNVlzd3R5d1Y3U1lkaldqK1l1VVY5bVJKMEtDUlU0V1pKTjFQYk5Zd3cvYU9jOW95TVRqK0dZMytCVDNQcW93Z3orb2pnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NDIsImFkdlNlY3JldEtleSI6InhuMFBQcy9CMWJnSnEyeTZqSzhGY0ZpL2ZBN09INi9sQk80blNDbGlWbG89IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjM0OTExNDIzODgwNEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIzQTgwOThBQkIzOUMyQUEwNEM3RSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzU0NTExMTAxfSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyMzQ5MTE0MjM4ODA0QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjNBMEE4Q0YyQTk2QjNDRDYyQzY3In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTQ1MTExMTV9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6Ikg5S1Y1TFlXIiwibWUiOnsiaWQiOiIyMzQ5MTE0MjM4ODA0OjIwQHMud2hhdHNhcHAubmV0IiwibmFtZSI6IkdyYW5kcGEgQ3lyaWwiLCJsaWQiOiIxMDA0NTEwMTM4ODYwOTA6MjBAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNPcUwrL01MRU96dHpzUUdHQU1nQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJkWWtHU3NQWTR3Z09ZbndQQkNLd0JJRSt4THZTdys0dkFnVVJ5bTZPUFZJPSIsImFjY291bnRTaWduYXR1cmUiOiJhNUFVSUtjcWNWcE8vMGhyS3g4Wk4rN0J4ZkVPRlpRa2I3WDh5Sk5aa2RTUnpJVmYwSThBOE1qeXRSMC9FK2xDTjErbmdJNkJCYXMwaEJKck5MUUZDZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiNk9RbUZRTEdJbm8zaUl5OGxwejRoVU5KbVhTZEk0eHQyUmlVT3lHVGxQdStsYlVPS2dXWEJoTEZnVjQ2K1BXc05oanBtUUNWRWJibmpZOEJuMmwwaUE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMzQ5MTE0MjM4ODA0OjIwQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlhXSkJrckQyT01JRG1KOER3UWlzQVNCUHNTNzBzUHVMd0lGRWNwdWpqMVMifX1dLCJwbGF0Zm9ybSI6InNtYmkiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNCSUlCUT09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc1NDUxMTA5OCwibGFzdFByb3BIYXNoIjoiMkc0QW11IiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFHd3EifQ==';
const appname = process.env.APP_NAME || '';
const herokuapi = process.env.HEROKU_API;
const botname = process.env.BOTNAME || '𝗥𝗔𝗩𝗘𝗡-𝗕𝗢𝗧';
const author = process.env.STICKER_AUTHOR || '𝗕𝗢𝗧';
const packname = process.env.STICKER_PACKNAME || '𝗥𝗔𝗩𝗘𝗡';
const dev = process.env.DEV || '254114660061';
const owner = dev.split(",");
const menulink = process.env.MENU_LINK || 'https://files.catbox.moe/duv8ac.jpg';
const menu = process.env.MENU_TYPE || 'VIDEO';
const bad = process.env.BAD_WORD || 'fuck';
const admin = process.env.ADMIN_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗿𝗲𝘀𝗲𝗿𝘃𝗲𝗱 𝗳𝗼𝗿 𝗔𝗱𝗺𝗶𝗻𝘀!';
const group = process.env.GROUP_ONLY_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝗚𝗿𝗼𝘂𝗽𝘀!';
const botAdmin = process.env.BOT_ADMIN_MSG || '𝗜 𝗻𝗲𝗲𝗱 𝗔𝗱𝗺𝗶𝗻 𝗽𝗿𝗲𝘃𝗶𝗹𝗲𝗱𝗴𝗲𝘀!';
const NotOwner = process.env.NOT_OWNER_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝘁𝗵𝗲 𝗼𝘄𝗻𝗲𝗿!';
const mycode = process.env.CODE || '234';
const port = process.env.PORT || 8080;
const databaseUrl = process.env.DATABASE_URL || '';

module.exports = {
  session,
  sessionName,
  author,
  packname,
  dev,
  owner,
  bad,
  group,
  NotOwner,
  botname,
  botAdmin, 
  menu,
  menulink,
  admin,
  mycode,
  herokuapi,
  port,
  appname,
  databaseUrl
};
